<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Internal\Resource\Productproperties\Patch;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Patch implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var int|null Product Property parent Id
     */
    private ?int $parent;

    /**
     * @var string|null Property name
     */
    private ?string $name;

    /**
     * @var string|null Property description
     */
    private ?string $description;

    /**
     * @var int|null Property position
     */
    private ?int $position;

    /**
     * @var string|null Base64 encoded Property icon
     */
    private ?string $icon;

    /**
     * @var string|null The property type
     */
    private ?string $type;

    public static function fromArray(array $data): static
    {
        return self::createFromArray($data);
    }

    /**
     * @return int|null Product Property parent Id
     */
    public function getParent(): ?int
    {
        return $this->parent;
    }

    /**
     * @return string|null Property name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return string|null Property description
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @return int|null Property position
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @return string|null Base64 encoded Property icon
     */
    public function getIcon(): ?string
    {
        return $this->icon;
    }

    /**
     * @return string|null The property type
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param int|null $parent Product Property parent Id
     * @return self
     */
    public function setParent(?int $parent): self
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * @param string|null $name Property name
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @param string|null $description Property description
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @param int|null $position Property position
     * @return self
     */
    public function setPosition(?int $position): self
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @param string|null $icon Base64 encoded Property icon
     * @return self
     */
    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;
        return $this;
    }

    /**
     * @param string|null $type The property type
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;
        return $this;
    }
}
