<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Endpoints;

use JacobDeKeizer\Ccv\Exceptions\CcvShopException;

/**
 * This class is autogenerated.
 */
class CreditpointsEndpoint extends BaseEndpoint
{
    /**
     * Gets a resource with creditpoints and a last mutation date. 150 per minute
     *
     * @throws CcvShopException
     */
    public function allFromUser(int $id): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Creditpoints\Creditpoints
    {
        $result = $this->doRequest(
            self::GET,
            'users/' . $id . '/creditpoints/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Creditpoints\Creditpoints::fromArray($result);
    }

    /**
     * Put the creditpoints of a user as is. 100 per minute
     *
     * @throws CcvShopException
     */
    public function updateForUser(int $id, \JacobDeKeizer\Ccv\Models\Internal\Resource\Creditpoints\Put\Put $model, bool $onlyFilled = true): void
    {
        $this->doRequest(
            self::PUT,
            'users/' . $id . '/creditpoints/',
            $model->toArray($onlyFilled)
        );
    }
}
