<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Endpoints;

use JacobDeKeizer\Ccv\Exceptions\CcvShopException;

/**
 * This class is autogenerated.
 */
class DashboardsEndpoint extends BaseEndpoint
{
    /**
     * Get all dashboards for this user. Each dashboard has a different name (ie location) with different blocks. 150 per minute
     *
     * @throws CcvShopException
     */
    public function all(): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Dashboards\Dashboards
    {
        $result = $this->doRequest(
            self::GET,
            'dashboards/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Dashboards\Dashboards::fromArray($result);
    }

    /**
     * Get one dashboard. 150 per minute
     *
     * @throws CcvShopException
     */
    public function get(int $id): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Dashboards\Dashboards
    {
        $result = $this->doRequest(
            self::GET,
            'dashboards/' . $id . '/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Dashboards\Dashboards::fromArray($result);
    }
}
