<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Endpoints;

use JacobDeKeizer\Ccv\Exceptions\CcvShopException;

/**
 * This class is autogenerated.
 */
class GeozonecountriesEndpoint extends BaseEndpoint
{
    /**
     * Retrieve all countries of the webshop's geozones. 150 per minute
     *
     * @throws CcvShopException
     */
    public function allFromWebshop(int $id): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Geozonecountries\Geozonecountries
    {
        $result = $this->doRequest(
            self::GET,
            'webshops/' . $id . '/geozonecountries/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Geozonecountries\Geozonecountries::fromArray($result);
    }
}
