<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Endpoints;

use JacobDeKeizer\Ccv\Exceptions\CcvShopException;

/**
 * This class is autogenerated.
 */
class LanguagesEndpoint extends BaseEndpoint
{
    /**
     * Get all available languages. 150 per minute
     *
     * @throws CcvShopException
     */
    public function all(): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Languages\Languages
    {
        $result = $this->doRequest(
            self::GET,
            'languages/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Languages\Languages::fromArray($result);
    }

    /**
     * Creates a new languages based upon an existing one. 100 per minute
     *
     * @throws CcvShopException
     */
    public function create(\JacobDeKeizer\Ccv\Models\Internal\Resource\Languages\Post\Post $model, bool $onlyFilled = true): \JacobDeKeizer\Ccv\Models\Internal\Resource\Languages\Resource\Post
    {
        $result = $this->doRequest(
            self::POST,
            'languages/',
            $model->toArray($onlyFilled)
        );

        return \JacobDeKeizer\Ccv\Models\Internal\Resource\Languages\Resource\Post::fromArray($result);
    }
}
