<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Endpoints;

use JacobDeKeizer\Ccv\Exceptions\CcvShopException;

/**
 * This class is autogenerated.
 */
class ProductstaggeredpricesEndpoint extends BaseEndpoint
{
    /**
     * Delete a staggered price row. 100 per minute
     *
     * @throws CcvShopException
     */
    public function delete(int $id): void
    {
        $this->doRequest(
            self::DELETE,
            'productstaggeredprices/' . $id . '/',
        );
    }

    /**
     * Get all straggered price rows of a product. 150 per minute
     *
     * @throws CcvShopException
     */
    public function allFromProduct(int $id, \JacobDeKeizer\Ccv\Parameters\Productstaggeredprices\AllFromProduct $parameter = null): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Productstaggeredprices\Productstaggeredprices
    {
        if ($parameter === null) {
            $parameter = new \JacobDeKeizer\Ccv\Parameters\Productstaggeredprices\AllFromProduct();
        }

        $result = $this->doRequest(
            self::GET,
            'products/' . $id . '/productstaggeredprices/' . $parameter->toBuilder()->toQueryString()
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Collection\Productstaggeredprices\Productstaggeredprices::fromArray($result);
    }

    /**
     * Get one staggered price row. 150 per minute
     *
     * @throws CcvShopException
     */
    public function get(int $id): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productstaggeredprices\Productstaggeredprices
    {
        $result = $this->doRequest(
            self::GET,
            'productstaggeredprices/' . $id . '/'
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productstaggeredprices\Productstaggeredprices::fromArray($result);
    }

    /**
     * Patch a staggered price row. 100 per minute
     *
     * @throws CcvShopException
     */
    public function update(int $id, \JacobDeKeizer\Ccv\Models\Internal\Resource\Productstaggeredprices\Input\Input $model, bool $onlyFilled = true): void
    {
        $this->doRequest(
            self::PATCH,
            'productstaggeredprices/' . $id . '/',
            $model->toArray($onlyFilled)
        );
    }

    /**
     * Post a staggered price row for this product. 100 per minute
     *
     * @throws CcvShopException
     */
    public function createForProduct(int $id, \JacobDeKeizer\Ccv\Models\Internal\Resource\Productstaggeredprices\Input\Input $model, bool $onlyFilled = true): \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productstaggeredprices\Productstaggeredprices
    {
        $result = $this->doRequest(
            self::POST,
            'products/' . $id . '/productstaggeredprices/',
            $model->toArray($onlyFilled)
        );

        return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productstaggeredprices\Productstaggeredprices::fromArray($result);
    }
}
