<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Internal\Resource\Producttocategories\Post;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Post implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var int|null Unique product position. When the position isn't filled the highest position will be used.
     */
    private ?int $position;

    /**
     * @var int Unique product id
     */
    private int $productId;

    /**
     * @var int Unique category id
     */
    private int $categoryId;

    /**
     * @return self
     */
    public static function fromArray(array $data): Model
    {
        return self::createFromArray($data);
    }

    /**
     * @return int|null Unique product position. When the position isn't filled the highest position will be used.
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @return int Unique product id
     */
    public function getProductId(): int
    {
        return $this->productId;
    }

    /**
     * @return int Unique category id
     */
    public function getCategoryId(): int
    {
        return $this->categoryId;
    }

    /**
     * @param int|null $position Unique product position. When the position isn't filled the highest position will be used.
     * @return self
     */
    public function setPosition(?int $position): self
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @param int $productId Unique product id
     * @return self
     */
    public function setProductId(int $productId): self
    {
        $this->productId = $productId;
        return $this;
    }

    /**
     * @param int $categoryId Unique category id
     * @return self
     */
    public function setCategoryId(int $categoryId): self
    {
        $this->categoryId = $categoryId;
        return $this;
    }
}
