<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Merchant implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string Link to self.
     */
    private string $href;

    /**
     * @var string|null Gender, can be null.
     */
    private ?string $gender;

    /**
     * @var string|null First name
     */
    private ?string $firstName;

    /**
     * @var string|null Last name
     */
    private ?string $lastName;

    /**
     * @var string|null Full name
     */
    private ?string $fullName;

    /**
     * @var string|null Company name
     */
    private ?string $company;

    /**
     * @var string|null E-mail address
     */
    private ?string $email;

    /**
     * @var string|null Address line
     */
    private ?string $addressLine;

    /**
     * @var string|null Street name
     */
    private ?string $street;

    /**
     * @var string|null House number with possible suffix
     */
    private ?string $housenumber;

    /**
     * @var string|null Zipcode
     */
    private ?string $zipcode;

    /**
     * @var string|null City
     */
    private ?string $city;

    /**
     * @var string|null Country full
     */
    private ?string $country;

    /**
     * @var string|null Country in 2 characters.
     */
    private ?string $countryCode;

    /**
     * @var string|null Telephone number
     */
    private ?string $telephone;

    /**
     * @var string|null Tax number
     */
    private ?string $taxNumber;

    /**
     * @var string|null Chamber of Commerce number
     */
    private ?string $cocNumber;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem|null Contains link to parent resource.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem $parent;

    public static function fromArray(array $data): static
    {
        return static::createFromArray($data);
    }

    /**
     * @return string Link to self.
     */
    public function getHref(): string
    {
        return $this->href;
    }

    /**
     * @return string|null Gender, can be null.
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * @return string|null First name
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @return string|null Last name
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * @return string|null Full name
     */
    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    /**
     * @return string|null Company name
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * @return string|null E-mail address
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @return string|null Address line
     */
    public function getAddressLine(): ?string
    {
        return $this->addressLine;
    }

    /**
     * @return string|null Street name
     */
    public function getStreet(): ?string
    {
        return $this->street;
    }

    /**
     * @return string|null House number with possible suffix
     */
    public function getHousenumber(): ?string
    {
        return $this->housenumber;
    }

    /**
     * @return string|null Zipcode
     */
    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    /**
     * @return string|null City
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @return string|null Country full
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * @return string|null Country in 2 characters.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * @return string|null Telephone number
     */
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    /**
     * @return string|null Tax number
     */
    public function getTaxNumber(): ?string
    {
        return $this->taxNumber;
    }

    /**
     * @return string|null Chamber of Commerce number
     */
    public function getCocNumber(): ?string
    {
        return $this->cocNumber;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem|null Contains link to parent resource.
     */
    public function getParent(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem
    {
        return $this->parent;
    }

    /**
     * @param string $href Link to self.
     * @return self
     */
    public function setHref(string $href): self
    {
        $this->href = $href;
        return $this;
    }

    /**
     * @param string|null $gender Gender, can be null.
     * @return self
     */
    public function setGender(?string $gender): self
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * @param string|null $firstName First name
     * @return self
     */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * @param string|null $lastName Last name
     * @return self
     */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * @param string|null $fullName Full name
     * @return self
     */
    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;
        return $this;
    }

    /**
     * @param string|null $company Company name
     * @return self
     */
    public function setCompany(?string $company): self
    {
        $this->company = $company;
        return $this;
    }

    /**
     * @param string|null $email E-mail address
     * @return self
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @param string|null $addressLine Address line
     * @return self
     */
    public function setAddressLine(?string $addressLine): self
    {
        $this->addressLine = $addressLine;
        return $this;
    }

    /**
     * @param string|null $street Street name
     * @return self
     */
    public function setStreet(?string $street): self
    {
        $this->street = $street;
        return $this;
    }

    /**
     * @param string|null $housenumber House number with possible suffix
     * @return self
     */
    public function setHousenumber(?string $housenumber): self
    {
        $this->housenumber = $housenumber;
        return $this;
    }

    /**
     * @param string|null $zipcode Zipcode
     * @return self
     */
    public function setZipcode(?string $zipcode): self
    {
        $this->zipcode = $zipcode;
        return $this;
    }

    /**
     * @param string|null $city City
     * @return self
     */
    public function setCity(?string $city): self
    {
        $this->city = $city;
        return $this;
    }

    /**
     * @param string|null $country Country full
     * @return self
     */
    public function setCountry(?string $country): self
    {
        $this->country = $country;
        return $this;
    }

    /**
     * @param string|null $countryCode Country in 2 characters.
     * @return self
     */
    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;
        return $this;
    }

    /**
     * @param string|null $telephone Telephone number
     * @return self
     */
    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;
        return $this;
    }

    /**
     * @param string|null $taxNumber Tax number
     * @return self
     */
    public function setTaxNumber(?string $taxNumber): self
    {
        $this->taxNumber = $taxNumber;
        return $this;
    }

    /**
     * @param string|null $cocNumber Chamber of Commerce number
     * @return self
     */
    public function setCocNumber(?string $cocNumber): self
    {
        $this->cocNumber = $cocNumber;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem|null $parent Contains link to parent resource.
     * @return self
     */
    public function setParent(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Entity\Merchant\Child\ParentItem $parent): self
    {
        $this->parent = $parent;
        return $this;
    }
}
