<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Appstorecategories implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string|null Link to self
     */
    private ?string $href;

    /**
     * @var int|null Unique id of the resource
     */
    private ?int $id;

    /**
     * @var string|null App store category name
     */
    private ?string $name;

    /**
     * @var string|null App store category description
     */
    private ?string $description;

    /**
     * @var int|null Position of the category
     */
    private ?int $position;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps|null Apps linked to this attribute.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps $apps;

    /**
     * @return self
     */
    public static function fromArray(array $data): Model
    {
        return self::createFromArray($data);
    }

    /**
     * @return string|null Link to self
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * @return int|null Unique id of the resource
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null App store category name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return string|null App store category description
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @return int|null Position of the category
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps|null Apps linked to this attribute.
     */
    public function getApps(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps
    {
        return $this->apps;
    }

    /**
     * @param string|null $href Link to self
     * @return self
     */
    public function setHref(?string $href): self
    {
        $this->href = $href;
        return $this;
    }

    /**
     * @param int|null $id Unique id of the resource
     * @return self
     */
    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string|null $name App store category name
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @param string|null $description App store category description
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @param int|null $position Position of the category
     * @return self
     */
    public function setPosition(?int $position): self
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps|null $apps Apps linked to this attribute.
     * @return self
     */
    public function setApps(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Appstorecategories\Child\Apps $apps): self
    {
        $this->apps = $apps;
        return $this;
    }
}
