<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Ordernotes implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string Link to self
     */
    private string $href;

    /**
     * @var int|null Order note id
     */
    private ?int $id;

    /**
     * @var string|null The text of this note.
     */
    private ?string $note;

    /**
     * @var string|null Type of this note. External notes are visible for customers too.
     */
    private ?string $type;

    /**
     * @var string|null The create date of the note in UTC
     */
    private ?string $createDate;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem|null Contains link to parent resource.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem $parent;

    public static function fromArray(array $data): static
    {
        return static::createFromArray($data);
    }

    /**
     * @return string Link to self
     */
    public function getHref(): string
    {
        return $this->href;
    }

    /**
     * @return int|null Order note id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null The text of this note.
     */
    public function getNote(): ?string
    {
        return $this->note;
    }

    /**
     * @return string|null Type of this note. External notes are visible for customers too.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @return string|null The create date of the note in UTC
     */
    public function getCreateDate(): ?string
    {
        return $this->createDate;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem|null Contains link to parent resource.
     */
    public function getParent(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem
    {
        return $this->parent;
    }

    /**
     * @param string $href Link to self
     * @return self
     */
    public function setHref(string $href): self
    {
        $this->href = $href;
        return $this;
    }

    /**
     * @param int|null $id Order note id
     * @return self
     */
    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string|null $note The text of this note.
     * @return self
     */
    public function setNote(?string $note): self
    {
        $this->note = $note;
        return $this;
    }

    /**
     * @param string|null $type Type of this note. External notes are visible for customers too.
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @param string|null $createDate The create date of the note in UTC
     * @return self
     */
    public function setCreateDate(?string $createDate): self
    {
        $this->createDate = $createDate;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem|null $parent Contains link to parent resource.
     * @return self
     */
    public function setParent(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Ordernotes\Child\ParentItem $parent): self
    {
        $this->parent = $parent;
        return $this;
    }
}
