<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Internal\Resource\Productvideos\Patch;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Patch implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string|null Productvideo name
     */
    private ?string $name;

    /**
     * @var int|null Productvideo position.
     */
    private ?int $position;

    /**
     * @var string|null Productvideo embedcode
     */
    private ?string $embedcode;

    public static function fromArray(array $data): static
    {
        return self::createFromArray($data);
    }

    /**
     * @return string|null Productvideo name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return int|null Productvideo position.
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @return string|null Productvideo embedcode
     */
    public function getEmbedcode(): ?string
    {
        return $this->embedcode;
    }

    /**
     * @param string|null $name Productvideo name
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @param int|null $position Productvideo position.
     * @return self
     */
    public function setPosition(?int $position): self
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @param string|null $embedcode Productvideo embedcode
     * @return self
     */
    public function setEmbedcode(?string $embedcode): self
    {
        $this->embedcode = $embedcode;
        return $this;
    }
}
