<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Productattributesets implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var int Attributeset id
     */
    private int $id;

    /**
     * @var string Attributeset name
     */
    private string $attributename;

    /**
     * @var int Attributeset position
     */
    private int $attributeposition;

    /**
     * @var string Attributeset type
     */
    private string $type;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\Items[] Collection of attribute values
     */
    private array $items;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem|null Contains link to parent product
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem $parent;

    public static function fromArray(array $data): static
    {
        return static::createFromArray($data);
    }

    /**
     * @return int Attributeset id
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string Attributeset name
     */
    public function getAttributename(): string
    {
        return $this->attributename;
    }

    /**
     * @return int Attributeset position
     */
    public function getAttributeposition(): int
    {
        return $this->attributeposition;
    }

    /**
     * @return string Attributeset type
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\Items[] Collection of attribute values
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem|null Contains link to parent product
     */
    public function getParent(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem
    {
        return $this->parent;
    }

    /**
     * @param int $id Attributeset id
     * @return self
     */
    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string $attributename Attributeset name
     * @return self
     */
    public function setAttributename(string $attributename): self
    {
        $this->attributename = $attributename;
        return $this;
    }

    /**
     * @param int $attributeposition Attributeset position
     * @return self
     */
    public function setAttributeposition(int $attributeposition): self
    {
        $this->attributeposition = $attributeposition;
        return $this;
    }

    /**
     * @param string $type Attributeset type
     * @return self
     */
    public function setType(string $type): self
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\Items ...$items $items Collection of attribute values
     * @return self
     */
    public function setItems(\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\Items ...$items): self
    {
        $this->items = $items;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem|null $parent Contains link to parent product
     * @return self
     */
    public function setParent(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productattributesets\Child\ParentItem $parent): self
    {
        $this->parent = $parent;
        return $this;
    }
}
