<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Apps implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string|null Link to self
     */
    private ?string $href;

    /**
     * @var int|null Unique id of the resource
     */
    private ?int $id;

    /**
     * @var string|null App Name
     */
    private ?string $name;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices|null The price of the app in Euros.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices $eurPrices;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices|null The price of the app in CHF.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices $chfPrices;

    /**
     * @var string|null The create date of the app.
     */
    private ?string $createDate;

    /**
     * @var string|null App Name
     */
    private ?string $modifiedDate;

    /**
     * @var string|null The description of the app.
     */
    private ?string $description;

    /**
     * @var string|null Cover image.
     */
    private ?string $cover;

    /**
     * @var string|null Logo image.
     */
    private ?string $logo;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer|null The developer of this app.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer $developer;

    /**
     * @var float|null The number how many times the app is installed.
     */
    private ?float $numberOfInstallations;

    /**
     * @var bool Marks if an app is installed in the webshop.
     */
    private bool $isInstalled;

    /**
     * @var string[]|null Array with available languages.
     */
    private ?array $availableLanguages;

    /**
     * @var string[]|null Array with available photos.
     */
    private ?array $photos;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories|null Collection of categories.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories $categories;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks|null Child resource of this resource. Contains all the code blocks associated with this app.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks $codeBlocks;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp|null Child resource of this resource. Contains all the Payment Service Providers associated with this app.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp $psp;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem|null Contains link to parent resource.
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem $parent;

    public static function fromArray(array $data): static
    {
        return self::createFromArray($data);
    }

    /**
     * @return string|null Link to self
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * @return int|null Unique id of the resource
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null App Name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices|null The price of the app in Euros.
     */
    public function getEurPrices(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices
    {
        return $this->eurPrices;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices|null The price of the app in CHF.
     */
    public function getChfPrices(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices
    {
        return $this->chfPrices;
    }

    /**
     * @return string|null The create date of the app.
     */
    public function getCreateDate(): ?string
    {
        return $this->createDate;
    }

    /**
     * @return string|null App Name
     */
    public function getModifiedDate(): ?string
    {
        return $this->modifiedDate;
    }

    /**
     * @return string|null The description of the app.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @return string|null Cover image.
     */
    public function getCover(): ?string
    {
        return $this->cover;
    }

    /**
     * @return string|null Logo image.
     */
    public function getLogo(): ?string
    {
        return $this->logo;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer|null The developer of this app.
     */
    public function getDeveloper(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer
    {
        return $this->developer;
    }

    /**
     * @return float|null The number how many times the app is installed.
     */
    public function getNumberOfInstallations(): ?float
    {
        return $this->numberOfInstallations;
    }

    /**
     * @return bool Marks if an app is installed in the webshop.
     */
    public function getIsInstalled(): bool
    {
        return $this->isInstalled;
    }

    /**
     * @return string[]|null Array with available languages.
     */
    public function getAvailableLanguages(): ?array
    {
        return $this->availableLanguages;
    }

    /**
     * @return string[]|null Array with available photos.
     */
    public function getPhotos(): ?array
    {
        return $this->photos;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories|null Collection of categories.
     */
    public function getCategories(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories
    {
        return $this->categories;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks|null Child resource of this resource. Contains all the code blocks associated with this app.
     */
    public function getCodeBlocks(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks
    {
        return $this->codeBlocks;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp|null Child resource of this resource. Contains all the Payment Service Providers associated with this app.
     */
    public function getPsp(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp
    {
        return $this->psp;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem|null Contains link to parent resource.
     */
    public function getParent(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem
    {
        return $this->parent;
    }

    /**
     * @param string|null $href Link to self
     * @return self
     */
    public function setHref(?string $href): self
    {
        $this->href = $href;
        return $this;
    }

    /**
     * @param int|null $id Unique id of the resource
     * @return self
     */
    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string|null $name App Name
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices|null $eurPrices The price of the app in Euros.
     * @return self
     */
    public function setEurPrices(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\EurPrices $eurPrices): self
    {
        $this->eurPrices = $eurPrices;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices|null $chfPrices The price of the app in CHF.
     * @return self
     */
    public function setChfPrices(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ChfPrices $chfPrices): self
    {
        $this->chfPrices = $chfPrices;
        return $this;
    }

    /**
     * @param string|null $createDate The create date of the app.
     * @return self
     */
    public function setCreateDate(?string $createDate): self
    {
        $this->createDate = $createDate;
        return $this;
    }

    /**
     * @param string|null $modifiedDate App Name
     * @return self
     */
    public function setModifiedDate(?string $modifiedDate): self
    {
        $this->modifiedDate = $modifiedDate;
        return $this;
    }

    /**
     * @param string|null $description The description of the app.
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @param string|null $cover Cover image.
     * @return self
     */
    public function setCover(?string $cover): self
    {
        $this->cover = $cover;
        return $this;
    }

    /**
     * @param string|null $logo Logo image.
     * @return self
     */
    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer|null $developer The developer of this app.
     * @return self
     */
    public function setDeveloper(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Developer $developer): self
    {
        $this->developer = $developer;
        return $this;
    }

    /**
     * @param float|null $numberOfInstallations The number how many times the app is installed.
     * @return self
     */
    public function setNumberOfInstallations(?float $numberOfInstallations): self
    {
        $this->numberOfInstallations = $numberOfInstallations;
        return $this;
    }

    /**
     * @param bool $isInstalled Marks if an app is installed in the webshop.
     * @return self
     */
    public function setIsInstalled(bool $isInstalled): self
    {
        $this->isInstalled = $isInstalled;
        return $this;
    }

    /**
     * @param string[]|null $availableLanguages Array with available languages.
     * @return self
     */
    public function setAvailableLanguages(?array $availableLanguages): self
    {
        $this->availableLanguages = $availableLanguages;
        return $this;
    }

    /**
     * @param string[]|null $photos Array with available photos.
     * @return self
     */
    public function setPhotos(?array $photos): self
    {
        $this->photos = $photos;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories|null $categories Collection of categories.
     * @return self
     */
    public function setCategories(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Categories $categories): self
    {
        $this->categories = $categories;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks|null $codeBlocks Child resource of this resource. Contains all the code blocks associated with this app.
     * @return self
     */
    public function setCodeBlocks(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\CodeBlocks $codeBlocks): self
    {
        $this->codeBlocks = $codeBlocks;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp|null $psp Child resource of this resource. Contains all the Payment Service Providers associated with this app.
     * @return self
     */
    public function setPsp(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\Psp $psp): self
    {
        $this->psp = $psp;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem|null $parent Contains link to parent resource.
     * @return self
     */
    public function setParent(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Apps\Child\ParentItem $parent): self
    {
        $this->parent = $parent;
        return $this;
    }
}
