<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Internal\Resource\Userproductadjustments\Patch;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Patch implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var float|null Adjusted price for this user for this product.
     */
    private ?float $price;

    /**
     * @var float|null Adjusted discount price for this user for this product. Must be NULL if price is NULL too.
     */
    private ?float $discount;

    /**
     * @var bool|null If TRUE then this product won't be visible for this user.
     */
    private ?bool $hidden;

    public static function fromArray(array $data): static
    {
        return self::createFromArray($data);
    }

    /**
     * @return float|null Adjusted price for this user for this product.
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @return float|null Adjusted discount price for this user for this product. Must be NULL if price is NULL too.
     */
    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    /**
     * @return bool|null If TRUE then this product won't be visible for this user.
     */
    public function getHidden(): ?bool
    {
        return $this->hidden;
    }

    /**
     * @param float|null $price Adjusted price for this user for this product.
     * @return self
     */
    public function setPrice(?float $price): self
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @param float|null $discount Adjusted discount price for this user for this product. Must be NULL if price is NULL too.
     * @return self
     */
    public function setDiscount(?float $discount): self
    {
        $this->discount = $discount;
        return $this;
    }

    /**
     * @param bool|null $hidden If TRUE then this product won't be visible for this user.
     * @return self
     */
    public function setHidden(?bool $hidden): self
    {
        $this->hidden = $hidden;
        return $this;
    }
}
