<?php

declare(strict_types=1);

namespace JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant;

use JacobDeKeizer\Ccv\Contracts\Model;
use JacobDeKeizer\Ccv\Traits\FromArray;
use JacobDeKeizer\Ccv\Traits\ToArray;

/**
 * This class is autogenerated.
 */
class Productrelevant implements Model
{
    use FromArray;
    use ToArray;

    /**
     * @var string Link to self
     */
    private string $href;

    /**
     * @var int Unique id of the resource
     */
    private int $id;

    /**
     * @var int Unique id of the child product. This is product will show on the parent product page as a relevant product.
     */
    private int $childProductId;

    /**
     * @var int Unique id of the parent product. This is product will show all the child product on the product page as relevant products.
     */
    private int $parentProductId;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct|null The child product
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct $childProduct;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct|null The parent product
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct $parentProduct;

    /**
     * @var \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem|null Parent resource of this resource
     */
    private ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem $parent;

    /**
     * @return self
     */
    public static function fromArray(array $data): Model
    {
        return self::createFromArray($data);
    }

    /**
     * @return string Link to self
     */
    public function getHref(): string
    {
        return $this->href;
    }

    /**
     * @return int Unique id of the resource
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return int Unique id of the child product. This is product will show on the parent product page as a relevant product.
     */
    public function getChildProductId(): int
    {
        return $this->childProductId;
    }

    /**
     * @return int Unique id of the parent product. This is product will show all the child product on the product page as relevant products.
     */
    public function getParentProductId(): int
    {
        return $this->parentProductId;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct|null The child product
     */
    public function getChildProduct(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct
    {
        return $this->childProduct;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct|null The parent product
     */
    public function getParentProduct(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct
    {
        return $this->parentProduct;
    }

    /**
     * @return \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem|null Parent resource of this resource
     */
    public function getParent(): ?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem
    {
        return $this->parent;
    }

    /**
     * @param string $href Link to self
     * @return self
     */
    public function setHref(string $href): self
    {
        $this->href = $href;
        return $this;
    }

    /**
     * @param int $id Unique id of the resource
     * @return self
     */
    public function setId(int $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param int $childProductId Unique id of the child product. This is product will show on the parent product page as a relevant product.
     * @return self
     */
    public function setChildProductId(int $childProductId): self
    {
        $this->childProductId = $childProductId;
        return $this;
    }

    /**
     * @param int $parentProductId Unique id of the parent product. This is product will show all the child product on the product page as relevant products.
     * @return self
     */
    public function setParentProductId(int $parentProductId): self
    {
        $this->parentProductId = $parentProductId;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct|null $childProduct The child product
     * @return self
     */
    public function setChildProduct(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ChildProduct $childProduct): self
    {
        $this->childProduct = $childProduct;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct|null $parentProduct The parent product
     * @return self
     */
    public function setParentProduct(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentProduct $parentProduct): self
    {
        $this->parentProduct = $parentProduct;
        return $this;
    }

    /**
     * @param \JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem|null $parent Parent resource of this resource
     * @return self
     */
    public function setParent(?\JacobDeKeizer\Ccv\Models\Vnd\Verto\Webshop\Resource\Productrelevant\Child\ParentItem $parent): self
    {
        $this->parent = $parent;
        return $this;
    }
}
